/**
 * vcharm Driver API
 * API for Vector's vcharm electric vehicle charging application
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@vector.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DriverProfilePreferences model module.
 * @module model/DriverProfilePreferences
 * @version 1.0.0
 */
class DriverProfilePreferences {
    /**
     * Constructs a new <code>DriverProfilePreferences</code>.
     * @alias module:model/DriverProfilePreferences
     */
    constructor() { 
        
        DriverProfilePreferences.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DriverProfilePreferences</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DriverProfilePreferences} obj Optional instance to populate.
     * @return {module:model/DriverProfilePreferences} The populated <code>DriverProfilePreferences</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DriverProfilePreferences();

            if (data.hasOwnProperty('language')) {
                obj['language'] = ApiClient.convertToType(data['language'], 'String');
            }
            if (data.hasOwnProperty('notificationsEnabled')) {
                obj['notificationsEnabled'] = ApiClient.convertToType(data['notificationsEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('units')) {
                obj['units'] = ApiClient.convertToType(data['units'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DriverProfilePreferences</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DriverProfilePreferences</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['language'] && !(typeof data['language'] === 'string' || data['language'] instanceof String)) {
            throw new Error("Expected the field `language` to be a primitive type in the JSON string but got " + data['language']);
        }
        // ensure the json data is a string
        if (data['units'] && !(typeof data['units'] === 'string' || data['units'] instanceof String)) {
            throw new Error("Expected the field `units` to be a primitive type in the JSON string but got " + data['units']);
        }

        return true;
    }


}



/**
 * @member {String} language
 */
DriverProfilePreferences.prototype['language'] = undefined;

/**
 * @member {Boolean} notificationsEnabled
 */
DriverProfilePreferences.prototype['notificationsEnabled'] = undefined;

/**
 * @member {module:model/DriverProfilePreferences.UnitsEnum} units
 */
DriverProfilePreferences.prototype['units'] = undefined;





/**
 * Allowed values for the <code>units</code> property.
 * @enum {String}
 * @readonly
 */
DriverProfilePreferences['UnitsEnum'] = {

    /**
     * value: "metric"
     * @const
     */
    "metric": "metric",

    /**
     * value: "imperial"
     * @const
     */
    "imperial": "imperial"
};



export default DriverProfilePreferences;

