/**
 * vcharm Driver API
 * API for Vector's vcharm electric vehicle charging application
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@vector.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ForgotPasswordResponse model module.
 * @module model/ForgotPasswordResponse
 * @version 1.0.0
 */
class ForgotPasswordResponse {
    /**
     * Constructs a new <code>ForgotPasswordResponse</code>.
     * @alias module:model/ForgotPasswordResponse
     */
    constructor() { 
        
        ForgotPasswordResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ForgotPasswordResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ForgotPasswordResponse} obj Optional instance to populate.
     * @return {module:model/ForgotPasswordResponse} The populated <code>ForgotPasswordResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ForgotPasswordResponse();

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('codeDeliveryDestination')) {
                obj['codeDeliveryDestination'] = ApiClient.convertToType(data['codeDeliveryDestination'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ForgotPasswordResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ForgotPasswordResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }
        // ensure the json data is a string
        if (data['codeDeliveryDestination'] && !(typeof data['codeDeliveryDestination'] === 'string' || data['codeDeliveryDestination'] instanceof String)) {
            throw new Error("Expected the field `codeDeliveryDestination` to be a primitive type in the JSON string but got " + data['codeDeliveryDestination']);
        }

        return true;
    }


}



/**
 * @member {String} message
 */
ForgotPasswordResponse.prototype['message'] = undefined;

/**
 * @member {String} codeDeliveryDestination
 */
ForgotPasswordResponse.prototype['codeDeliveryDestination'] = undefined;






export default ForgotPasswordResponse;

