/**
 * vcharm Driver API
 * API for Vector's vcharm electric vehicle charging application
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@vector.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VehicleDetailAllOfSettingsPreferredChargingTimes model module.
 * @module model/VehicleDetailAllOfSettingsPreferredChargingTimes
 * @version 1.0.0
 */
class VehicleDetailAllOfSettingsPreferredChargingTimes {
    /**
     * Constructs a new <code>VehicleDetailAllOfSettingsPreferredChargingTimes</code>.
     * @alias module:model/VehicleDetailAllOfSettingsPreferredChargingTimes
     */
    constructor() { 
        
        VehicleDetailAllOfSettingsPreferredChargingTimes.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VehicleDetailAllOfSettingsPreferredChargingTimes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VehicleDetailAllOfSettingsPreferredChargingTimes} obj Optional instance to populate.
     * @return {module:model/VehicleDetailAllOfSettingsPreferredChargingTimes} The populated <code>VehicleDetailAllOfSettingsPreferredChargingTimes</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VehicleDetailAllOfSettingsPreferredChargingTimes();

            if (data.hasOwnProperty('dayOfWeek')) {
                obj['dayOfWeek'] = ApiClient.convertToType(data['dayOfWeek'], 'Number');
            }
            if (data.hasOwnProperty('startTime')) {
                obj['startTime'] = ApiClient.convertToType(data['startTime'], 'String');
            }
            if (data.hasOwnProperty('endTime')) {
                obj['endTime'] = ApiClient.convertToType(data['endTime'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VehicleDetailAllOfSettingsPreferredChargingTimes</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VehicleDetailAllOfSettingsPreferredChargingTimes</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['startTime'] && !(typeof data['startTime'] === 'string' || data['startTime'] instanceof String)) {
            throw new Error("Expected the field `startTime` to be a primitive type in the JSON string but got " + data['startTime']);
        }
        // ensure the json data is a string
        if (data['endTime'] && !(typeof data['endTime'] === 'string' || data['endTime'] instanceof String)) {
            throw new Error("Expected the field `endTime` to be a primitive type in the JSON string but got " + data['endTime']);
        }

        return true;
    }


}



/**
 * @member {Number} dayOfWeek
 */
VehicleDetailAllOfSettingsPreferredChargingTimes.prototype['dayOfWeek'] = undefined;

/**
 * @member {String} startTime
 */
VehicleDetailAllOfSettingsPreferredChargingTimes.prototype['startTime'] = undefined;

/**
 * @member {String} endTime
 */
VehicleDetailAllOfSettingsPreferredChargingTimes.prototype['endTime'] = undefined;






export default VehicleDetailAllOfSettingsPreferredChargingTimes;

