/**
 * vcharm Driver API
 * API for Vector's vcharm electric vehicle charging application
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@vector.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ChargingSession from '../model/ChargingSession';
import CurrentChargingSession from '../model/CurrentChargingSession';

/**
* Charging service.
* @module api/ChargingApi
* @version 1.0.0
*/
export default class ChargingApi {

    /**
    * Constructs a new ChargingApi. 
    * @alias module:api/ChargingApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getChargingHistory operation.
     * @callback module:api/ChargingApi~getChargingHistoryCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/ChargingSession>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get charging history
     * Returns the charging history for a specific vehicle
     * @param {String} driverId ID of the driver
     * @param {String} vehicleId ID of the vehicle
     * @param {Object} opts Optional parameters
     * @param {Date} [from] Start date for filtering (ISO 8601)
     * @param {Date} [to] End date for filtering (ISO 8601)
     * @param {Number} [limit = 20)] Maximum number of records to return
     * @param {Number} [offset = 0)] Number of records to skip
     * @param {module:api/ChargingApi~getChargingHistoryCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/ChargingSession>}
     */
    getChargingHistory(driverId, vehicleId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'driverId' is set
      if (driverId === undefined || driverId === null) {
        throw new Error("Missing the required parameter 'driverId' when calling getChargingHistory");
      }
      // verify the required parameter 'vehicleId' is set
      if (vehicleId === undefined || vehicleId === null) {
        throw new Error("Missing the required parameter 'vehicleId' when calling getChargingHistory");
      }

      let pathParams = {
        'driver_id': driverId,
        'vehicle_id': vehicleId
      };
      let queryParams = {
        'from': opts['from'],
        'to': opts['to'],
        'limit': opts['limit'],
        'offset': opts['offset']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [ChargingSession];
      return this.apiClient.callApi(
        '/drivers/{driver_id}/vehicles/{vehicle_id}/charging-sessions', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getCurrentChargingSession operation.
     * @callback module:api/ChargingApi~getCurrentChargingSessionCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CurrentChargingSession} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get current charging session
     * Returns information about the current charging session for a specific vehicle
     * @param {String} driverId ID of the driver
     * @param {String} vehicleId ID of the vehicle
     * @param {module:api/ChargingApi~getCurrentChargingSessionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CurrentChargingSession}
     */
    getCurrentChargingSession(driverId, vehicleId, callback) {
      let postBody = null;
      // verify the required parameter 'driverId' is set
      if (driverId === undefined || driverId === null) {
        throw new Error("Missing the required parameter 'driverId' when calling getCurrentChargingSession");
      }
      // verify the required parameter 'vehicleId' is set
      if (vehicleId === undefined || vehicleId === null) {
        throw new Error("Missing the required parameter 'vehicleId' when calling getCurrentChargingSession");
      }

      let pathParams = {
        'driver_id': driverId,
        'vehicle_id': vehicleId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = CurrentChargingSession;
      return this.apiClient.callApi(
        '/drivers/{driver_id}/vehicles/{vehicle_id}/charging-sessions/current', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
