/**
 * vcharm Driver API
 * API for Vector's vcharm electric vehicle charging application
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@vector.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import DriverProfile from '../model/DriverProfile';
import Vehicle from '../model/Vehicle';
import VehicleDetail from '../model/VehicleDetail';

/**
* Drivers service.
* @module api/DriversApi
* @version 1.0.0
*/
export default class DriversApi {

    /**
    * Constructs a new DriversApi. 
    * @alias module:api/DriversApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getDriverProfile operation.
     * @callback module:api/DriversApi~getDriverProfileCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DriverProfile} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get driver profile information
     * Returns the profile information for a specific driver
     * @param {String} driverId ID of the driver
     * @param {module:api/DriversApi~getDriverProfileCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DriverProfile}
     */
    getDriverProfile(driverId, callback) {
      let postBody = null;
      // verify the required parameter 'driverId' is set
      if (driverId === undefined || driverId === null) {
        throw new Error("Missing the required parameter 'driverId' when calling getDriverProfile");
      }

      let pathParams = {
        'driver_id': driverId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DriverProfile;
      return this.apiClient.callApi(
        '/drivers/{driver_id}/profile', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getDriverVehicles operation.
     * @callback module:api/DriversApi~getDriverVehiclesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Vehicle>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all vehicles for a driver
     * Returns a list of vehicles for a specific driver
     * @param {String} driverId ID of the driver
     * @param {module:api/DriversApi~getDriverVehiclesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Vehicle>}
     */
    getDriverVehicles(driverId, callback) {
      let postBody = null;
      // verify the required parameter 'driverId' is set
      if (driverId === undefined || driverId === null) {
        throw new Error("Missing the required parameter 'driverId' when calling getDriverVehicles");
      }

      let pathParams = {
        'driver_id': driverId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Vehicle];
      return this.apiClient.callApi(
        '/drivers/{driver_id}/vehicles', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getVehicleInfo operation.
     * @callback module:api/DriversApi~getVehicleInfoCallback
     * @param {String} error Error message, if any.
     * @param {module:model/VehicleDetail} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get vehicle information
     * Returns detailed information for a specific vehicle
     * @param {String} driverId ID of the driver
     * @param {String} vehicleId ID of the vehicle
     * @param {module:api/DriversApi~getVehicleInfoCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/VehicleDetail}
     */
    getVehicleInfo(driverId, vehicleId, callback) {
      let postBody = null;
      // verify the required parameter 'driverId' is set
      if (driverId === undefined || driverId === null) {
        throw new Error("Missing the required parameter 'driverId' when calling getVehicleInfo");
      }
      // verify the required parameter 'vehicleId' is set
      if (vehicleId === undefined || vehicleId === null) {
        throw new Error("Missing the required parameter 'vehicleId' when calling getVehicleInfo");
      }

      let pathParams = {
        'driver_id': driverId,
        'vehicle_id': vehicleId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = VehicleDetail;
      return this.apiClient.callApi(
        '/drivers/{driver_id}/vehicles/{vehicle_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
