/**
 * vcharm Driver API
 * API for Vector's vcharm electric vehicle charging application
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@vector.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import DriverProfile from '../model/DriverProfile';

/**
* Profile service.
* @module api/ProfileApi
* @version 1.0.0
*/
export default class ProfileApi {

    /**
    * Constructs a new ProfileApi. 
    * @alias module:api/ProfileApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getDriverProfile operation.
     * @callback module:api/ProfileApi~getDriverProfileCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DriverProfile} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get driver profile information
     * Returns the profile information for a specific driver
     * @param {String} driverId ID of the driver
     * @param {module:api/ProfileApi~getDriverProfileCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DriverProfile}
     */
    getDriverProfile(driverId, callback) {
      let postBody = null;
      // verify the required parameter 'driverId' is set
      if (driverId === undefined || driverId === null) {
        throw new Error("Missing the required parameter 'driverId' when calling getDriverProfile");
      }

      let pathParams = {
        'driver_id': driverId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DriverProfile;
      return this.apiClient.callApi(
        '/drivers/{driver_id}/profile', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
