/**
 * vcharm Driver API
 * API for Vector's vcharm electric vehicle charging application
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@vector.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ChargingSessionChargingCurveInner model module.
 * @module model/ChargingSessionChargingCurveInner
 * @version 1.0.0
 */
class ChargingSessionChargingCurveInner {
    /**
     * Constructs a new <code>ChargingSessionChargingCurveInner</code>.
     * @alias module:model/ChargingSessionChargingCurveInner
     */
    constructor() { 
        
        ChargingSessionChargingCurveInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ChargingSessionChargingCurveInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ChargingSessionChargingCurveInner} obj Optional instance to populate.
     * @return {module:model/ChargingSessionChargingCurveInner} The populated <code>ChargingSessionChargingCurveInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChargingSessionChargingCurveInner();

            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Date');
            }
            if (data.hasOwnProperty('powerKw')) {
                obj['powerKw'] = ApiClient.convertToType(data['powerKw'], 'Number');
            }
            if (data.hasOwnProperty('batteryLevel')) {
                obj['batteryLevel'] = ApiClient.convertToType(data['batteryLevel'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ChargingSessionChargingCurveInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ChargingSessionChargingCurveInner</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Date} timestamp
 */
ChargingSessionChargingCurveInner.prototype['timestamp'] = undefined;

/**
 * @member {Number} powerKw
 */
ChargingSessionChargingCurveInner.prototype['powerKw'] = undefined;

/**
 * @member {Number} batteryLevel
 */
ChargingSessionChargingCurveInner.prototype['batteryLevel'] = undefined;






export default ChargingSessionChargingCurveInner;

