/**
 * vcharm Driver API
 * API for Vector's vcharm electric vehicle charging application
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@vector.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Vehicle model module.
 * @module model/Vehicle
 * @version 1.0.0
 */
class Vehicle {
    /**
     * Constructs a new <code>Vehicle</code>.
     * @alias module:model/Vehicle
     */
    constructor() { 
        
        Vehicle.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Vehicle</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Vehicle} obj Optional instance to populate.
     * @return {module:model/Vehicle} The populated <code>Vehicle</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Vehicle();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('make')) {
                obj['make'] = ApiClient.convertToType(data['make'], 'String');
            }
            if (data.hasOwnProperty('model')) {
                obj['model'] = ApiClient.convertToType(data['model'], 'String');
            }
            if (data.hasOwnProperty('year')) {
                obj['year'] = ApiClient.convertToType(data['year'], 'Number');
            }
            if (data.hasOwnProperty('licensePlate')) {
                obj['licensePlate'] = ApiClient.convertToType(data['licensePlate'], 'String');
            }
            if (data.hasOwnProperty('batteryCapacity')) {
                obj['batteryCapacity'] = ApiClient.convertToType(data['batteryCapacity'], 'Number');
            }
            if (data.hasOwnProperty('currentBatteryLevel')) {
                obj['currentBatteryLevel'] = ApiClient.convertToType(data['currentBatteryLevel'], 'Number');
            }
            if (data.hasOwnProperty('isCharging')) {
                obj['isCharging'] = ApiClient.convertToType(data['isCharging'], 'Boolean');
            }
            if (data.hasOwnProperty('lastSeen')) {
                obj['lastSeen'] = ApiClient.convertToType(data['lastSeen'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Vehicle</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Vehicle</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['make'] && !(typeof data['make'] === 'string' || data['make'] instanceof String)) {
            throw new Error("Expected the field `make` to be a primitive type in the JSON string but got " + data['make']);
        }
        // ensure the json data is a string
        if (data['model'] && !(typeof data['model'] === 'string' || data['model'] instanceof String)) {
            throw new Error("Expected the field `model` to be a primitive type in the JSON string but got " + data['model']);
        }
        // ensure the json data is a string
        if (data['licensePlate'] && !(typeof data['licensePlate'] === 'string' || data['licensePlate'] instanceof String)) {
            throw new Error("Expected the field `licensePlate` to be a primitive type in the JSON string but got " + data['licensePlate']);
        }

        return true;
    }


}



/**
 * @member {String} id
 */
Vehicle.prototype['id'] = undefined;

/**
 * @member {String} name
 */
Vehicle.prototype['name'] = undefined;

/**
 * @member {String} make
 */
Vehicle.prototype['make'] = undefined;

/**
 * @member {String} model
 */
Vehicle.prototype['model'] = undefined;

/**
 * @member {Number} year
 */
Vehicle.prototype['year'] = undefined;

/**
 * @member {String} licensePlate
 */
Vehicle.prototype['licensePlate'] = undefined;

/**
 * Battery capacity in kWh
 * @member {Number} batteryCapacity
 */
Vehicle.prototype['batteryCapacity'] = undefined;

/**
 * Current battery level in percentage
 * @member {Number} currentBatteryLevel
 */
Vehicle.prototype['currentBatteryLevel'] = undefined;

/**
 * @member {Boolean} isCharging
 */
Vehicle.prototype['isCharging'] = undefined;

/**
 * @member {Date} lastSeen
 */
Vehicle.prototype['lastSeen'] = undefined;






export default Vehicle;

