/**
 * vcharm Driver API
 * API for Vector's vcharm electric vehicle charging application
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@vector.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.VcharmDriverApi);
  }
}(this, function(expect, VcharmDriverApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new VcharmDriverApi.ForgotPasswordRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ForgotPasswordRequest', function() {
    it('should create an instance of ForgotPasswordRequest', function() {
      // uncomment below and update the code to test ForgotPasswordRequest
      //var instance = new VcharmDriverApi.ForgotPasswordRequest();
      //expect(instance).to.be.a(VcharmDriverApi.ForgotPasswordRequest);
    });

    it('should have the property username (base name: "username")', function() {
      // uncomment below and update the code to test the property username
      //var instance = new VcharmDriverApi.ForgotPasswordRequest();
      //expect(instance).to.be();
    });

  });

}));
